### ISSUE TITLE
如何实现coder2.0的效果

### ISSUE THREAD

**Issue by deadpoppy** [Hexo-Minimalist/Coder#5]
下载了你的文件展示的效果为1.0效果，但是想要的是你所展示的2.0效果，找不到教程，请求指教

**Comment by 0x01x0** [comment]
> 下载了你的文件展示的效果为1.0效果，但是想要的是你所展示的2.0效果，找不到教程，请求指教

作者删教程了 不知道为啥 😭😭

**Comment by ZonaHu** [comment]
> 下载了你的文件展示的效果为1.0效果，但是想要的是你所展示的2.0效果，找不到教程，请求指教

Demo效果还没有Update上来 可以持续关注一下～

**Comment by Xunzhuo** [comment]
2.0目前还在测试中哈

**Comment by deadpoppy** [comment]
被2.0效果吸引过来，可惜看到的是1.0的代码，有点失望

**Comment by Xunzhuo** [comment]
如果喜欢2.0效果 可关注这个Repo 我将单独出一个这个主题，因为和 1.0风格差太大。https://github.com/Hexo-Minimalist/CardFlow
